### ISSUE TITLE
91st Amateur Series Division 8 underway with live web-based broadcast

### ISSUE THREAD

**Issue by GrahamCCRL** [analog-hors/tantabus#4]
91ST AMATEUR SERIES (Division 8 )

Intel i7 Quad
ChessGUI
256mb hash each
3-4-5 piece tablebases
Ponder off
GM2700+.cgb book
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 44 rounds
All engines 64-bit where available

The top engine will gain automatic promotion. Any other changes of division will be at my discretion and may not necessarily involve playoff matches.

Participants

Weiawaga 4.0 64-bit (new)
Loki 3.5.0 64-bit (relegated)
Waxman 2020
MinimalChess 0.6 64-bit
Cosette 5.1 64-bit
NoC 4.20 64-bit
Popochin 4.2 64-bit
Ares GB 1.1 64-bit
Tantabus 1.0.2 64-bit (new)
Isa 2.0.83 64-bit
Barbarossa 0.6.0 64-bit
Anka 0.6.3 64-bit

Games and standings will be available after every six rounds from the following link:
http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?f=7&t=13836

Web based link for live viewing (huge thanks to Jay - Berserk author).
http://tlcv.net/16092

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your computer, you can watch the games live move by move. You'll also be able to chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959
Host - GrahamCCRL.dyndns.org Port - 16092

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by analog-hors** [comment]
Thanks for letting me know. For future reference, you can reach me at analog-pone-4ef8@outlook.com.
